version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 443:443
      - 8888:8888 #TODO: 80に変更
    environment:
      HTTP_PORT: 8888 # TODO: 削除
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - $CERTS_DIR:/etc/nginx/certs:ro
      - $LETSENCRYPT_LIVE_DIR:/etc/letsencrypt/live:ro
      - $LETSENCRYPT_ARCHIVE_DIR:/etc/letsencrypt/archive:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: "bridge"
    privileged: true
    restart: always
volumes:
  conf:
  vhost:
  html:
